blueprint:
  name: Report offline zigbee/zwave/battery/smart plug devices
  description: Can be configured to run periodically based on a time pattern.
  domain: automation
  input:
    time_pattern_hours:
      name: Hourly Period
      description: Trigger automation at every X hours
      default: 1
      selector:
        number:
          min: 0
          max: 23
          mode: slider
          step: 1
    time_pattern_minutes:
      name: Minute Period
      description: Trigger automation at every X minutes
      default: 0
      selector:
        number:
          min: 0
          max: 59
          mode: slider
          step: 1
    exclude:
      name: Excluded Sensors
      description: Battery sensors to exclude from detection.
      default:
        entity_id: []
      selector:
        target:
          entity:
          - device_class:
              - battery
              - switch
    actions:
      name: Actions
      description: Call your notification here. {{offline_devices}} will be replaced with the name of any offline devices
      selector:
        action: {}

  source_url: https://gist.github.com/Tahutipai/971bf0e07e50ce6190e0dacd73262e2e

# Variable definitions here...
variables:
  day: !input day
  exclude: !input exclude
  offline_devices: "{% set result = namespace(offline_devices=[]) %} {% for sensor
    in states.sensor | selectattr('attributes.device_class', 'defined') | selectattr('attributes.device_class',
    '==', 'battery') %}\n  {% if \"unavailable\" in sensor | string  and not sensor.entity_id
    in exclude.entity_id %}\n    {% set result.offline_devices = result.offline_devices
    + [device_attr(device_id(sensor.entity_id), \"name\")] %}\n  {% endif %}\n{% endfor
    %} {% for binary_sensor in states.binary_sensor | selectattr('attributes.device_class',
    'defined') | selectattr('attributes.device_class', '==', 'battery') %}\n  {% if
    \"unavailable\" in binary_sensor | string and not binary_sensor.entity_id in exclude.entity_id
    %}\n    {% set result.offline_devices = result.offline_devices + [device_attr(device_id(binary_sensor.entity_id),
    \"name\")] %}\n  {% endif %}\n{% endfor %} {% for switch in states.switch | selectattr('state','eq','unavailable')
    %}\n  {% if switch.entity_id not in exclude.entity_id %}\n    {% set result.offline_devices
    = result.offline_devices + [device_attr(device_id(switch.entity_id), \"name\")]
    %}\n  {% endif %}\n{% endfor %} {{result.offline_devices|sort|unique|join('\\n')}}"

trigger:
  - platform: time_pattern
    hours: !input time_pattern_hours
    minutes: !input time_pattern_minutes

condition:
  - '{{ offline_devices != '''' }}'

action:
  - choose: []
    default: !input actions

mode: single
